
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'EQUALS GT ID LT LTSLASH STRING TEXTdocument : contentelement : LT ID attributes GT content LTSLASH ID GTelement : TEXTattributes : attributes attribute\n| emptyattribute : ID EQUALS STRINGcontent : content element\n| emptyempty :'
    
_lr_action_items = {'LT':([0,2,3,4,6,11,14,18,],[-9,5,-8,-7,-3,-9,5,-2,]),'TEXT':([0,2,3,4,6,11,14,18,],[-9,6,-8,-7,-3,-9,6,-2,]),'$end':([0,1,2,3,4,6,18,],[-9,0,-1,-8,-7,-3,-2,]),'LTSLASH':([3,4,6,11,14,18,],[-8,-7,-3,-9,16,-2,]),'ID':([5,7,8,9,12,15,16,],[7,-9,10,-5,-4,-6,17,]),'GT':([7,8,9,12,15,17,],[-9,11,-5,-4,-6,18,]),'EQUALS':([10,],[13,]),'STRING':([13,],[15,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'document':([0,],[1,]),'content':([0,11,],[2,14,]),'empty':([0,7,11,],[3,9,3,]),'element':([2,14,],[4,4,]),'attributes':([7,],[8,]),'attribute':([8,],[12,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> document","S'",1,None,None,None),
  ('document -> content','document',1,'p_document','25CS60R86.py',89),
  ('element -> LT ID attributes GT content LTSLASH ID GT','element',8,'p_element_node','25CS60R86.py',99),
  ('element -> TEXT','element',1,'p_element_text','25CS60R86.py',126),
  ('attributes -> attributes attribute','attributes',2,'p_attributes','25CS60R86.py',134),
  ('attributes -> empty','attributes',1,'p_attributes','25CS60R86.py',135),
  ('attribute -> ID EQUALS STRING','attribute',3,'p_attribute','25CS60R86.py',147),
  ('content -> content element','content',2,'p_content','25CS60R86.py',152),
  ('content -> empty','content',1,'p_content','25CS60R86.py',153),
  ('empty -> <empty>','empty',0,'p_empty','25CS60R86.py',161),
]
